### ISSUE TITLE
Adding refactor/docs/style commits to generated release notes

### ISSUE THREAD

**Issue by samlevin** [semantic-release/release-notes-generator#148] opened 2019-11-01 06:34 UTC
I've configured commit-analyzer to flag `docs`, `refactor`, and `style` as patch releases. It's working as intended but the release-notes-generator output seems to only include `feat` and `fix` types by default, resulting in blank release notes for a version in which only any of these three types exist. Is it possible to override this behavior?

are the release notes regenerated from scratch on every release? or are only the latest commits appended to whatever is already there? (wondering if this can self-heal provided I can find a workaround for the above)

`.releaserc`
```
{
  "tagFormat": "${version}",
  "plugins": [
    ["@semantic-release/commit-analyzer", {
      "preset": "angular",
      "releaseRules": [
        {"type": "docs", "scope":"README", "release": "patch"},
        {"type": "refactor", "release": "patch"},
        {"type": "style", "release": "patch"}
      ],
      "parserOpts": {
        "noteKeywords": ["BREAKING CHANGE", "BREAKING CHANGES"]
      }
    }],
    "@semantic-release/release-notes-generator",
    ["@semantic-release/npm", {
      "npmPublish": false
    }],
    ["@semantic-release/changelog", {
      "changelogFile": "CHANGELOG.md",
    }],
    ["@semantic-release/git", {
      "message": "ci(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }]
  ]
}```

**Comment by pvdlg** [comment] 2019-11-01 15:33
Please see the followings that all answer the same question:
- https://github.com/semantic-release/release-notes-generator/issues/115
- https://github.com/semantic-release/release-notes-generator/issues/77
- https://github.com/semantic-release/release-notes-generator/issues/142
- https://github.com/semantic-release/changelog/issues/38
- https://stackoverflow.com/questions/58639452/semantic-release-release-notes-generator-how-to-teach-new-types

Please remember to use the GitHub search function before opening a new issue.

**Comment by pvdlg** [comment] 2019-11-01 15:33
Duplicate of #77

**Closed as completed by pvdlg** 2019-11-01 15:33 UTC
Labels: plugin:release-notes, support
