### ISSUE TITLE
How can I custom type that include in release note?

### ISSUE THREAD

**Issue by kamontat** [semantic-release/release-notes-generator#115] opened 2018-12-09 14:05 UTC

**Comment by pvdlg** [comment] 2018-12-10 00:00
So you already opened the exact same issue in https://github.com/semantic-release/changelog/issues/38. Why that? Opening multiple identical issues is not going to get you an answer faster, just create an unwelcome and unpleasant pressure on the maintainer team.

Instead of opening multiple identical issues, I invite you to read out [contributing guideline](https://github.com/semantic-release/semantic-release/blob/master/CONTRIBUTING.md#using-the-issue-tracker) that specifies:
> The issue tracker is the channel for [bug reports](#bug-report), [features requests](#feature-request) and [submitting pull requests](#submitting-a-pull-request) only. Please use the [Support](docs/support/README.md) and [Get help](README.md#get-help) sections for support, troubleshooting and questions.

> Before opening an issue or a Pull Request, please use the [GitHub issue search](https://github.com/issues?utf8=%E2%9C%93&q=user%3Asemantic-release) to make sure the bug or feature request hasn't been already reported or fixed.

This question has already been answered in https://github.com/semantic-release/release-notes-generator/issues/77.

**Comment by pvdlg** [comment] 2018-12-10 00:00
Duplicate of #77

**Closed as completed by pvdlg** 2018-12-10 00:00 UTC
Labels: support
