### ISSUE TITLE
How to add presets to release notes?

### ISSUE THREAD

**Issue by rodoabad** [semantic-release/release-notes-generator#142] opened 2019-09-20 14:27 UTC
Assuming I have this option.

```
        [
            "@semantic-release/commit-analyzer",
            {
                "preset": "angular",
                "releaseRules": [
                    {
                        "release": "patch",
                        "type": "ci"
                    },
                    {
                        "release": "patch",
                        "type": "docs"
                    },
                    {
                        "release": "patch",
                        "type": "refactor"
                    }
                ]
            }
        ]
```

When release notes are released, `refactor`, `ci`, and `docs` aren't being shown in our release notes.

**Comment by pvdlg** [comment] 2019-09-23 17:04
Duplicate of #77

**Closed as completed by pvdlg** 2019-09-23 17:04 UTC
